name: C/C++ CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: 安装 依赖
      run: sudo apt update && sudo apt upgrade -y && sudo apt install -y ccache libdebuginfod1
      
    - name: configure
      run: chmod +x build.sh && ./build.sh
