name: C/C++ CI

on:
  push:
    branches: [ "13" ]
  pull_request:
    branches: [ "13" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: 安装 依赖
      run: sudo apt update && sudo apt upgrade -y && sudo apt install -y ccache python3 git curl build-essential libssl-dev bison flex libelf-dev dwarves
      
    - name: configure
      run: chmod +x build.sh && ./build.sh
